### ISSUE TITLE
Add support for reading from objects and multiple sources

### ISSUE THREAD

**Issue by droyad** [ConfigInjectorContributors/ConfigInjector#9]
I've implemented an ObjectSettingsReader and MultipleSourceSettingsReader (https://gist.github.com/droyad/809e97e5c969f4c4e851) in my project. The object comes from NDesk.Options, but could also be from a config file section, etc.

They are generic, so do you want me to integrate them and send a PR?

**Comment by droyad** [comment]
The MultipleSourceSettingsReader also allows the overriding of settings from a different source (say command line vs config)

**Comment by uglybugger** [comment]
I've pulled in your gist for the ObjectSettingsReader (thank you :) ) and will merge it to master shortly.

There's separate functionality for overriding settings so that we can ensure that base-level settings still exist before overriding them. I gave some thought to the generic MultipleSourceSettingsReader approach a while ago and worried that it would be setting traps for people for the common case. I'll give that some more thought, though :)
